### ISSUE TITLE
Support remote names other than origin

### ISSUE THREAD

**Issue by jayvdb** [vcstools/vcstools#126] opened 2017-11-18 16:07 UTC
Effectively the same as https://github.com/vcstools/wstool/issues/59

There is https://github.com/vcstools/vcstools/tree/allow_other_remote by @tkruse .
Merging that would be a good start.

My dev team [prefers](http://coala.io/git) that newcomers do not have an `origin` as they get confused by it, so we recommend `upstream` and `<username>`, so they have to think about it (esp. when running random commands they find on the internet)

@guyzmo's [git-repo](https://github.com/guyzmo/git-repo/) also has `upstream` as a special remote name for the central repository where all forks come from.

c.f. similar request at https://github.com/mgedmin/ghcloneall/issues/2

**Comment by tkruse** [comment] 2017-11-19 02:33
Hi John, well done finding my old branch. That branch would use a different remote name if only one remote is defined, but on checkout, it would still use origin. So that might be even more confusing.

Also not sure about your motivation. Onboarding git newcomers is a hassle, but changing the git defaults just for that seems the wrong way to go. Restricting force-pushes on the server side, or telling your newcomers to use a safer git client might be more useful.

**Comment by jayvdb** [comment] 2017-11-19 03:21
Currently if they checkout using another tool, with a git remote other than `origin`, currently wstool spits out

```
local-name  V  git master < upstream/master  (-)  1f4633eea955     (github.com/abc/def)
```

It can't find the remote name, so believes it is different.  I believe your patch will fix this part of the workflow.

The ability to checkout using a different origin name is also important, and is quite simple for `vcstools` to provide this ability.  Of course it would default to `origin`, so would be 100% backwards compatible with previous versions of vcstools.  It is then up to the cli tools how they expose this functionality to end-users.  fwiw, I would be very happy if it was an override `--origin` flag like `git clone` provides.

How cli tools use these capabilities, and how other orgs onboard new users, is a bit beyond the scope of this issue in this library. ;-)

**Comment by tkruse** [comment] 2017-11-20 00:23
So far usually we tried not to add as many features as possible to these tools, but rather features that bring enough value to many teams. so a discussion about whether the use-case is relevant enough also requires consideration of alternative solutions to the root problem. If your team went back to using 'origin', you would not need the feature. It is possible your team might do so after this discussion, that would be cheaper then implementing the feature. It is easy to implement something in terms of lines to change, but hard to implement in terms of necessary discussions and approvals, and regression testing all commands with a different remote would also be painful.

So we should discuss what use cases we need to support and why.

Preventing force pushes seems like the only thing you'd really want to prevent, though I am not even sure you prevent them by using a different remote name. All git commands work without providing any remote name.

Regarding the design: the CLI tools we use check out multiple different repositories at once. So would we have to support changing the remote name individually, or for all repositories? Would this concern git only or more VCSes? For your users, would they have to remember for each CLI command that might check out a repo depending on filesystem state to pass the option to change the remote name? 

Possibly wstools should define variables for all defaults used, and CLI tools should allow to change those defaults via enc variables or via rcfiles. Possibly the CLI tools in ROS using vcstools should allow plugins so that teams like yours using unconventional workflows can adapt the tools more without requiring changes to ROS Tools.

**Comment by jayvdb** [comment] 2017-11-20 02:58
We're not going to change our processes to suit the tool. We have other tools which also rely on this, as I mentioned in my opening post.  We onboard hundreds of high school and uni students per year.  We do rigorous code review on thousands of PRs per year.  We build our newcomer processes to make this scalable.  Students who dont RTFM are rejected, and typically can't proceed to get a Google Summer of Code project with us.  Likewise Google Code-in.  There is an abundance of interested & talented developers; we filter out those who dont want to learn processes.  Try to stand in our shoes before telling us to change.

If the "vcstools" group of tools don't work for us, we'll build/enhance another tool that suit our processes.  Next stop is https://github.com/dirk-thomas/vcstool .

Of the 50 repos in my `.rosinstall` (which is a subset of [our orgs working set](https://github.com/jayvdb/meta/tree/rosinstall/rosinstall) that I am investigating ), only two are `svn` and two are `hg`, and I am fairly sure that there are git mirrors of the `svn` repos, and I could do the same with the `hg` repos, so we could easily switch to Android's [`repo`](https://android.googlesource.com/tools/repo), and I have also been looking at [gitshelf](http://github.com/gitshelf/gitshelf/).


This repo is just a library, providing useful features so other tools can be built using them.  The discussion about design of `wstool`, or other tools, comes after the raw functionality exists in `vcstools`.

Regarding vcstool 'design', the ability to choose a remote name *obviously* would be available for any VCS which have the ability to have multiple named remotes (i.e. especially `git` and `hg`, and `bzr` has an equivalent) and where the toolchain works correctly with an alternative name.  Basically every DVCS.  As a new optional feature, it doesnt need to be implemented for them all.  Like `shallow`, which isnt available for all VCS, and isnt implemented for VCS where an equivalent is possible.

So, the `allow_other_remote` branch.  I think you should cache the output of `_get_default_remote` in an `@property`, but otherwise that could be merged, and then someone else .. me? .. adds a new optional arg to `VcsClient.checkout` for `local_uri_name`?  When None, the VCS layer would default to its own default, or ignore, depending on whatever is the default behaviour.  And that patch would be able to add end-to-end tests for git, because `allow_other_remote` branch has allowed the repo to work after it is checked out with a different origin name.

**Comment by tkruse** [comment] 2017-11-21 01:46
I meant no offense by suggesting a change of workflow using git defaults.

And indeed there are a lot of vcs command multiplexers around, in particular for git. Also note that for ROS2, the OSRF guys try to make the vcstool project that you pointed out replace wstool.

I am not a maintainer, btw, just a long-term contributor.


I expect you would have to create the respective PRs for wstool and vcstools yourself. Feel free to use the changes from my old branch as you see fit. Though parts of it had already been merged ('origin' now returned by _get_default_remote()

In your place I would run patched versions of wstool and vcstools locally first to validate the result works for you and your users, then make 2 PRs at the same time.

Possibly you can pass a different default remote name in the initializer / a setter, and thus avoid any call to git to get the name of remotes by parsing shell output. That would be less prone to break (with different git versions, locales, etc), and thus a less expensive / risky change.

**Comment by dirk-thomas** [comment] 2020-06-25 15:20
Closing since the repository is about to be archived: see #166.

**Closed by dirk-thomas** 2020-06-25 15:20 UTC
Labels: enhancement
